### ISSUE TITLE
Problem with image links

### ISSUE THREAD

**Issue by kbingman** [olivernn/davis.js#2] opened 2011-04-04 13:35 UTC
It looks like linking an image instead of text breaks davis. Of course it degrades gracefully, but an error message briefly shows, and then the normal link is activated. I tried to trace the error message, but could not find it, even with a breakpoint. Have you seen this behavior?

**Comment by olivernn** [comment] 2011-04-04 13:52
I hadn't seen this before but am able to reproduce it with the latest version, 0.3.2.  It happens whenever a link contains another element, in your case an img.  I'll take a look and get a fix applied.

P.S. In cases like this where there is an error on a link click handler and it is difficult to debug because the error message is not displayed on the new page load you can use Firebug's 'persist' button, this will make sure the error message is visible even on the new page load.

**Comment by olivernn** [comment] 2011-04-04 17:14
I've just pushed version 0.3.3 which solves this bug, please update your version of Davis and let me know if you are still having any problems.

**Comment by olivernn** [comment] 2011-04-05 13:43
Closing this issue as it is fixed in latest version

**Closed as completed by olivernn** 2011-04-05 13:43 UTC
